name: trade_now
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  firebase_auth: ^5.3.0
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_image_compress: ^2.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
